# zmodload zsh/zprof # Uncomment for profiling

[ -f ~/.zshrclocal ] && source ~/.zshrclocal
source ~/dotfiles/configs/shell/main.sh

# zprof # Uncomment for profiling

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
