#!/bin/bash

# Fix SSH auth socket location so agent forwarding works with tmux.
# from https://stackoverflow.com/a/23187030
if test "$SSH_AUTH_SOCK" ; then
  ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi
