## enable or disable automatic sync
auto_sync = true

## enable or disable automatic update checks
update_check = false

[stats]
# Set commands where we should consider the subcommand for statistics. Eg, kubectl get vs just kubectl
common_subcommands = [
 "git",
 "g",
 "uv",
]

[theme]
name = "autumn"


[daemon]
enabled = false